import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { expect, test, vi } from "vitest";
import type { LibraryApi } from "../../lib/api";
import type { ExportPlan } from "../../lib/contracts";
import { ExportDialog } from "./ExportDialog";
const plan: ExportPlan = { id:"plan-1",target:"/tmp/Portraits",portraitCount:2,requiresConfirmation:true,warnings:["Saved-game references are not migrated."],actions:[{kind:"overwrite",path:"/tmp/Portraits/current/Small.png",reason:"Existing file"},{kind:"remove",path:"/tmp/Portraits/old/Small.png",reason:"Old portrait"},{kind:"preserve",path:"/tmp/Portraits/notes.txt",reason:"Unrelated content"}] };
function api(overrides: Partial<LibraryApi> = {}) { return {queryCatalog:vi.fn().mockImplementation((q)=>Promise.resolve({items:[],total:q.selectedOnly ? 2 : 300,revision:1})),getSavedDestinations:vi.fn().mockResolvedValue([]),planExport:vi.fn().mockResolvedValue(plan),designateExportTarget:vi.fn().mockResolvedValue("/tmp/Portraits"),discardExportPlan:vi.fn().mockResolvedValue(undefined),validateExportPlan:vi.fn().mockResolvedValue(plan),applyExport:vi.fn().mockResolvedValue({id:"job",state:"running",completed:0,total:2,message:"Exporting"}),...overrides} as unknown as LibraryApi; }
async function preview() {fireEvent.change(screen.getByLabelText("Export target"),{target:{value:"/tmp/Portraits"}});fireEvent.click(screen.getByRole("button",{name:"Preview export"}));await screen.findByText("2 frozen portraits");}
test("shows full active and persisted selection counts; never applies before exact confirmation",async()=>{const a=api();render(<ExportDialog api={a} onClose={()=>{}}/>);await screen.findByText("All active portraits (300)");expect(screen.getByText("Persisted selection (2)")).toBeInTheDocument();await preview();expect(a.applyExport).not.toHaveBeenCalled();expect(screen.getByText("/tmp/Portraits/old/Small.png")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Confirm overwrite"}));await waitFor(()=>expect(a.applyExport).toHaveBeenCalledWith("plan-1",true));expect(a.validateExportPlan).toHaveBeenCalledWith("plan-1");});
test("replacement requires explicit collection designation and exact confirmation",async()=>{const a=api();render(<ExportDialog api={a} onClose={()=>{}}/>);fireEvent.change(screen.getByLabelText("Export mode"),{target:{value:"replace"}});fireEvent.change(screen.getByLabelText("Export target"),{target:{value:"/tmp/Portraits"}});expect(screen.getByRole("button",{name:"Preview export"})).toBeDisabled();fireEvent.click(screen.getByLabelText("Use this exact directory as a portrait collection"));fireEvent.click(screen.getByRole("button",{name:"Preview export"}));await screen.findByText("2 frozen portraits");expect(a.designateExportTarget).toHaveBeenCalledWith("/tmp/Portraits");fireEvent.click(screen.getByRole("button",{name:"Confirm replacement"}));await waitFor(()=>expect(a.applyExport).toHaveBeenCalledWith("plan-1",true));});
test.each(["target","scope","mode","output"])("editing %s retires the preview",async(field)=>{const a=api();render(<ExportDialog api={a} onClose={()=>{}}/>);await preview();const names={target:"Export target",scope:"Export scope",mode:"Export mode",output:"Export output"};const values={target:"/tmp/other",scope:"selected",mode:"replace",output:"zip"};fireEvent.change(screen.getByLabelText(names[field as keyof typeof names]),{target:{value:values[field as keyof typeof values]}});expect(screen.queryByText("2 frozen portraits")).not.toBeInTheDocument();expect(a.discardExportPlan).toHaveBeenCalledWith("plan-1");expect(a.applyExport).not.toHaveBeenCalled();});
test("stale destination prevents apply and asks for a fresh preview",async()=>{const a=api({validateExportPlan:vi.fn().mockRejectedValue({message:"The destination changed. Preview again."})});render(<ExportDialog api={a} onClose={()=>{}}/>);await preview();fireEvent.click(screen.getByRole("button",{name:"Confirm overwrite"}));await screen.findByRole("alert");expect(a.applyExport).not.toHaveBeenCalled();expect(screen.queryByText("2 frozen portraits")).not.toBeInTheDocument();});
test("late preview after editing is discarded; cancel does not apply",async()=>{let resolve!:(p:ExportPlan)=>void;const a=api({planExport:vi.fn().mockReturnValue(new Promise<ExportPlan>(r=>{resolve=r;}))});const close=vi.fn();render(<ExportDialog api={a} onClose={close}/>);fireEvent.change(screen.getByLabelText("Export target"),{target:{value:"/tmp/Portraits"}});fireEvent.click(screen.getByRole("button",{name:"Preview export"}));fireEvent.change(screen.getByLabelText("Export target"),{target:{value:"/tmp/other"}});resolve(plan);await waitFor(()=>expect(a.discardExportPlan).toHaveBeenCalledWith("plan-1"));expect(screen.queryByText("2 frozen portraits")).not.toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Cancel"}));expect(close).toHaveBeenCalled();expect(a.applyExport).not.toHaveBeenCalled();});
test("production planning-only API keeps confirmation unavailable without fake apply",async()=>{const a=api({applyExport:undefined});render(<ExportDialog api={a} onClose={()=>{}}/>);await preview();expect(screen.getByRole("button",{name:"Confirm overwrite"})).toBeDisabled();expect(screen.getByText(/Export writing is not available/)).toBeInTheDocument();});
test("nonstandard dimension confirmation says confirm export when no files are overwritten",async()=>{const a=api({planExport:vi.fn().mockResolvedValue({...plan,actions:[{kind:"add",path:"/tmp/Portraits/new/Small.png",reason:"New file"}],warnings:["Nonstandard dimensions"]})});render(<ExportDialog api={a} onClose={()=>{}}/>);await preview();expect(screen.getByRole("button",{name:"Confirm export"})).toBeEnabled();});
