use portrait_core::{Library, types::JobState};
use portrait_manager_lib::state::DesktopState;
use std::{
    path::PathBuf,
    time::{Duration, Instant},
};
use uuid::Uuid;
fn finish(state: &DesktopState, id: Uuid) {
    let deadline = Instant::now() + Duration::from_secs(10);
    loop {
        let job = state.job(id).unwrap().unwrap();
        if job.state != JobState::Running {
            assert_eq!(job.state, JobState::Done, "{}", job.message);
            break;
        }
        assert!(Instant::now() < deadline);
        std::thread::sleep(Duration::from_millis(10));
    }
}
#[test]
fn portable_jobs_confirm_exact_path_restore_identity_and_have_scoped_acl() {
    let temp = tempfile::tempdir().unwrap();
    let state = DesktopState::new(temp.path().join("settings"));
    let source = state
        .activate(Library::create(&temp.path().join("source")).unwrap())
        .unwrap();
    let path = temp.path().join("backup.zip");
    let job = state.start_backup(path.clone(), None).unwrap();
    finish(&state, job.id);
    assert_eq!(
        state
            .start_backup(path.clone(), Some(PathBuf::from("wrong.zip")))
            .unwrap_err()
            .code,
        "BACKUP_CONFIRMATION_REQUIRED"
    );
    let job = state
        .start_backup(path.clone(), Some(path.clone()))
        .unwrap();
    finish(&state, job.id);
    assert!(
        state
            .start_restore(path.clone(), temp.path().join("restored"))
            .is_err()
    );
    state.close().unwrap();
    let job = state
        .start_restore(path, temp.path().join("restored"))
        .unwrap();
    finish(&state, job.id);
    assert_eq!(
        state.restored_library(job.id).unwrap().unwrap().id,
        source.id
    );
    let capability = include_str!("../capabilities/default.json");
    for command in ["start_backup", "start_restore", "get_restore_result"] {
        assert!(capability.contains(&format!("allow-{}", command.replace('_', "-"))));
        let permission = std::fs::read_to_string(format!(
            "{}/permissions/autogenerated/{command}.toml",
            env!("CARGO_MANIFEST_DIR")
        ))
        .unwrap();
        assert!(permission.contains(&format!("commands.allow = [\"{command}\"]")));
    }
}
