use portrait_core::{
    Library,
    types::{ExportMode, ExportOutput, ExportRequest, ExportScope},
};
use portrait_manager_lib::state::DesktopState;
#[test]
fn desktop_planner_is_read_only_and_registry_closes_with_library() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("library");
    let target = temp.path().join("collection");
    let state = DesktopState::new(temp.path().join("config"));
    state.activate(Library::create(&root).unwrap()).unwrap();
    let request = ExportRequest {
        scope: ExportScope::All,
        target: target.clone(),
        output: ExportOutput::Directory,
        mode: ExportMode::Replace,
    };
    assert_eq!(
        state.plan_export(request.clone()).unwrap_err().code,
        "EXPORT_TARGET_NOT_DESIGNATED"
    );
    assert_eq!(
        state.designate_export_target(target.clone()).unwrap(),
        target
    );
    let plan = state.plan_export(request.clone()).unwrap();
    assert!(plan.requires_confirmation);
    assert_eq!(plan.portrait_count, 0);
    assert!(state.validate_export_plan(plan.id).is_ok());
    assert!(!target.exists());
    state.discard_export_plan(plan.id).unwrap();
    assert_eq!(
        state.validate_export_plan(plan.id).unwrap_err().code,
        "EXPORT_PLAN_NOT_FOUND"
    );
    let plan = state.plan_export(request).unwrap();
    state.close().unwrap();
    state.activate(Library::open(&root).unwrap()).unwrap();
    assert_eq!(
        state.validate_export_plan(plan.id).unwrap_err().code,
        "EXPORT_PLAN_NOT_FOUND"
    );
    assert!(!target.exists());
}
#[test]
fn every_export_command_has_an_explicit_permission_and_capability() {
    let root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let capability: serde_json::Value =
        serde_json::from_slice(&std::fs::read(root.join("capabilities/default.json")).unwrap())
            .unwrap();
    let build = std::fs::read_to_string(root.join("build.rs")).unwrap();
    let handler = std::fs::read_to_string(root.join("src/lib.rs")).unwrap();
    for name in [
        "plan_export",
        "designate_export_target",
        "validate_export_plan",
        "discard_export_plan",
    ] {
        let permission =
            std::fs::read_to_string(root.join(format!("permissions/autogenerated/{name}.toml")))
                .unwrap();
        assert!(permission.contains(&format!("commands.allow = [\"{name}\"]")));
        assert!(
            capability["permissions"]
                .as_array()
                .unwrap()
                .iter()
                .any(|p| p.as_str() == Some(&format!("allow-{}", name.replace('_', "-"))))
        );
        assert!(build.contains(&format!("\"{name}\"")));
        assert!(handler.contains(&format!("commands::{name}")));
    }
}
