use portrait_core::{
    Library,
    import::{JobContext, import_portraits},
    types::*,
};
use portrait_manager_lib::state::DesktopState;
use std::{
    fs, thread,
    time::{Duration, Instant},
};
fn seeded(root: &std::path::Path) -> Library {
    let mut l = Library::create(root).unwrap();
    let source = root.parent().unwrap().join("source");
    fs::create_dir_all(&source).unwrap();
    for name in ["Small.png", "Medium.png", "Fulllength.png"] {
        image::RgbaImage::from_pixel(2, 3, image::Rgba([20, 30, 40, 255]))
            .save(source.join(name))
            .unwrap();
    }
    import_portraits(
        &mut l,
        ImportRequest {
            path: source,
            source_name: "test".into(),
            kind: ImportKind::Folder,
            resize: false,
            duplicate_policy: Default::default(),
        },
        &JobContext::default(),
    )
    .unwrap();
    l
}
fn wait(state: &DesktopState, id: uuid::Uuid) -> Job {
    let until = Instant::now() + Duration::from_secs(10);
    loop {
        let j = state.job(id).unwrap().unwrap();
        if j.state != JobState::Running {
            return j;
        }
        assert!(Instant::now() < until);
        thread::sleep(Duration::from_millis(10));
    }
}
#[test]
fn export_jobs_persist_history_by_independent_target_identity() {
    let t = tempfile::tempdir().unwrap();
    let root = t.path().join("library");
    let config = t.path().join("config");
    let state = DesktopState::new(config.clone());
    state.activate(seeded(&root)).unwrap();
    let request = ExportRequest {
        target: t.path().join("out"),
        scope: ExportScope::All,
        output: ExportOutput::Directory,
        mode: ExportMode::Merge,
    };
    let plan = state.plan_export(request.clone()).unwrap();
    assert_eq!(
        state.apply_export(plan.id, false).unwrap_err().code,
        "EXPORT_CONFIRMATION_REQUIRED"
    );
    let job = state.apply_export(plan.id, true).unwrap();
    assert_eq!(wait(&state, job.id).state, JobState::Done);
    assert_eq!(state.export_report(job.id).unwrap().unwrap().added, 3);
    state.close().unwrap();
    drop(state);
    let state = DesktopState::new(config.clone());
    state.activate(Library::open(&root).unwrap()).unwrap();
    let plan = state.plan_export(request.clone()).unwrap();
    assert!(
        plan.actions
            .iter()
            .all(|a| a.reason.contains("Previously exported"))
    );
    assert!(plan.requires_confirmation);
    let old = t.path().join("old");
    fs::rename(&request.target, &old).unwrap();
    fs::create_dir(&request.target).unwrap();
    for folder in fs::read_dir(&old).unwrap() {
        let f = folder.unwrap();
        let dest = request.target.join(f.file_name());
        fs::create_dir(&dest).unwrap();
        for file in fs::read_dir(f.path()).unwrap() {
            let file = file.unwrap();
            fs::copy(file.path(), dest.join(file.file_name())).unwrap();
        }
    }
    let plan = state.plan_export(request).unwrap();
    assert!(plan.actions.iter().all(|a| a.reason.contains("Unknown")));
}
#[test]
fn apply_and_report_commands_have_explicit_acl() {
    let root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let capability = fs::read_to_string(root.join("capabilities/default.json")).unwrap();
    for command in ["apply_export", "get_export_report"] {
        let permission =
            fs::read_to_string(root.join(format!("permissions/autogenerated/{command}.toml")))
                .unwrap();
        assert!(permission.contains(&format!("commands.allow = [\"{command}\"]")));
        assert!(capability.contains(&format!("allow-{}", command.replace('_', "-"))));
        assert!(
            fs::read_to_string(root.join("build.rs"))
                .unwrap()
                .contains(&format!("\"{command}\""))
        );
        assert!(
            fs::read_to_string(root.join("src/lib.rs"))
                .unwrap()
                .contains(&format!("commands::{command}"))
        );
    }
}
#[test]
fn committed_export_keeps_a_receipt_when_history_write_fails_and_retries_on_open() {
    let t = tempfile::tempdir().unwrap();
    let root = t.path().join("library");
    let config = t.path().join("config");
    let state = DesktopState::new(config.clone());
    state.activate(seeded(&root)).unwrap();
    let request = ExportRequest {
        target: t.path().join("out"),
        scope: ExportScope::All,
        output: ExportOutput::Directory,
        mode: ExportMode::Merge,
    };
    let p = state.plan_export(request.clone()).unwrap();
    let history = config.join("export-history.json");
    let before = fs::read(&history).unwrap();
    fs::remove_file(&history).unwrap();
    fs::create_dir(&history).unwrap();
    let job = state.apply_export(p.id, true).unwrap();
    assert_eq!(wait(&state, job.id).state, JobState::Done);
    let report = state.export_report(job.id).unwrap().unwrap();
    assert_eq!(report.added, 3);
    assert!(
        report
            .issues
            .iter()
            .any(|i| i.code == "EXPORT_HISTORY_ERROR")
    );
    state.close().unwrap();
    fs::remove_dir(&history).unwrap();
    fs::write(&history, before).unwrap();
    state.activate(Library::open(&root).unwrap()).unwrap();
    let p = state.plan_export(request).unwrap();
    assert!(
        p.actions
            .iter()
            .all(|a| a.reason.contains("Previously exported"))
    );
}
#[test]
fn saved_destination_identity_is_separate_and_recreation_does_not_inherit_history() {
    let t = tempfile::tempdir().unwrap();
    let root = t.path().join("library");
    let state = DesktopState::new(t.path().join("config"));
    state.activate(seeded(&root)).unwrap();
    let request = ExportRequest {
        target: t.path().join("out"),
        scope: ExportScope::All,
        output: ExportOutput::Directory,
        mode: ExportMode::Merge,
    };
    let p = state.plan_export(request.clone()).unwrap();
    let job = state.apply_export(p.id, true).unwrap();
    assert_eq!(wait(&state, job.id).state, JobState::Done);
    let mut saved = Destination {
        id: uuid::Uuid::new_v4(),
        path: request.target.clone(),
        game: Game::Kingmaker,
        name: "Saved".into(),
        origin: DestinationOrigin::Manual,
        state: DestinationState::Existing,
        evidence: vec![],
    };
    state.save_destination(saved.clone()).unwrap();
    let p = state.plan_export(request.clone()).unwrap();
    assert!(p.actions.iter().all(|a| a.reason.contains("Unknown")));
    let job = state.apply_export(p.id, true).unwrap();
    assert_eq!(wait(&state, job.id).state, JobState::Done);
    let p = state.plan_export(request.clone()).unwrap();
    assert!(
        p.actions
            .iter()
            .all(|a| a.reason.contains("Previously exported"))
    );
    saved.id = uuid::Uuid::new_v4();
    state.save_destination(saved).unwrap();
    let p = state.plan_export(request).unwrap();
    assert!(p.actions.iter().all(|a| a.reason.contains("Unknown")));
}
