[[permission]]
identifier = "allow-change-selection"
description = "Enables the change_selection command."
commands.allow = ["change_selection"]

[[permission]]
identifier = "deny-change-selection"
description = "Denies the change_selection command."
commands.deny = ["change_selection"]
